### ISSUE TITLE
User Profile Update

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Backend#19]
![image](https://user-images.githubusercontent.com/44530828/79015894-5b42da80-7b8b-11ea-8207-b74d156b756b.png)

Details that is included in the user profile update is as above. Do the necessary changes to the backend as required.

**Comment by dilinipeirs** [comment]
![image](https://user-images.githubusercontent.com/28673959/79041306-68ec7480-7c0c-11ea-9afb-5072d0306a93.png)
dont let the user see the current password.. 
In fact i am not sending the current password to the frontend.. so the value u are setting here is actually garbage value.
![image](https://user-images.githubusercontent.com/28673959/79041516-275cc900-7c0e-11ea-88e8-b209387b9768.png)

make him enter the current password, new password and confirm new password.. you have to have some frontend logic here accordingly..

for eg: if the user typed new password and confirm new password are equal set the details as follows:
the current password to the 'password' field
the new password to the 'newPassword' field
![image](https://user-images.githubusercontent.com/28673959/79041410-57f03300-7c0d-11ea-8f25-80058c268968.png)


then from the backend i will check if the current password is correct. And only if it is correct i will be changing it to the new password.

**Comment by Nethmi96** [comment]
yeah, it was a mistake. i forgot to comment it.
do we have to get the confirm new password as well? normally isn't it only current password and new password? 
and in the profile update form user can update any details regarding them as follows.
![image](https://user-images.githubusercontent.com/44530828/79043159-30a06280-7c1b-11ea-8bc5-c9eec1c3e2ca.png)
![image](https://user-images.githubusercontent.com/44530828/79043180-401fab80-7c1b-11ea-8849-0121542e5a19.png)

**Comment by dilinipeirs** [comment]
Ok let's not ask to confirm new password because you have entered the 'eye' for the user to check whether they have typed it correctly.

1. But please check whether you have put the validator for the new password textbox. I think you have forgotten that.
![image](https://user-images.githubusercontent.com/28673959/79044896-b9bc9700-7c25-11ea-87eb-b78d2f1ca612.png)


2. I think we dont need to have both a registered address and shipping address.. Let's have one address only. And if the person want to get it delivered to another address, at the checkout we can ask them to put another address, and then maybe ask them whether they would like to update the address or use it only for that particular order.
Therefore please have only **'address'**

3. **Dont let the user update their username and email..** have those fields uneditable. Because then if a third party person logs into our system, then the person can change all the data in the profile and make that account inaccessible to the actual owner of the account.

4. add postal code and city also to this profile page -> because u took them when registering to the system

**Comment by Nethmi96** [comment]
1. Password validator included.
2. yeah true and also I want to mention that here what i considered as **adderess** is what we took as **city** in the registration process. 
3. Made username and email fileds readonly.
4. Postal code is included and **city ** in the registration form is renamed into address.
